version: '3.8'

services:
  waha:
    image: devlikeapro/waha
    container_name: waha
    ports:
      - "8082:3000"
    environment:
      - WAHA_LOG_FORMAT=JSON
      - WAHA_LOG_LEVEL=info
      - WAHA_NO_API_KEY=True
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=adminadmin123
      - WHATSAPP_SWAGGER_USERNAME=admin
      - WHATSAPP_SWAGGER_PASSWORD=adminadmin123
    restart: always
